### ISSUE TITLE
Feature proposition

### ISSUE THREAD

**Issue by MichelVGameMaker** [Ailwuful/LDtk-Room_builder#1]
Hello,

I use your previous version for a while. And I plan to use it again soon. Thank you for this!

If this helps you: I decided to add the following features.
1-Import entities **scales defined in LDtk**. So I parse this from the LDtk json and change the XScale, YScale value in the .yy file
2-Allow the user to **use image_angle, image_index, image_speed in fields for LDtk** so that the values are writen in the .yy file
3-**Import other fields** defined by the user in LDtk. (For this to work, a variable with the proper name needs to be defined in Game Maker variable definition... otherwise GM find a variable in the room .yy but not in the object .yy and it decides to delete the variable from the room.

**If this helps, how did I do it:**
0-Before looping in layers I store entities def (.defs.entities in th json) to **store width, height, pivotX, pivotY**. I do it in a temporary/local struct called **_ent_def_struct** based on entity's  __identifier
Then when looping in entities array to create instances, for each instance; 
(For reference my loop in entities is :
	var _entities   = _this_layer.entityInstances;
	var _ent_number = array_length(_entities); 
for (var _ent = 0; _ent < _ent_number; _ent++) )

1- For image_xscale / yscale : I simply calculate them based on an entity size vs the one in the def section
	var _scalex   = string(_entities[_ent].width  / **_ent_def_struct**[$ _entities[_ent].__identifier].width);
	var _scaley   = string(_entities[_ent].height / **_ent_def_struct**[$ _entities[_ent].__identifier].height);

2- For image_angle, image_index, image_speed and 3-get other fields, it's done at the same time:
// Prepare default values for image_angle, image_frame, image_speed. Those can be overiden if the entity has those variables/fields defined within LDTK
var _im_angle = 0;
var _im_frame = 0;
var _im_speed = 1;				
// Build variable definitions for all fields, Please not that the variable should already exist in GMS object variable definitions with the same name as the field from LDTK. Otherwise it will not be kept by Game Maker
var _fields     = _entities[_ent].fieldInstances;
var _fld_number = array_length(_fields);
if (_fld_number > 0) {
	var _props  = "[";	
	for (var _fld = 0; _fld < _fld_number; _fld++) {
		var _field_name  = string(_fields[_fld].__identifier);
		var _field_value = string(_fields[_fld].__value);
		if      (_field_name == "image_angle") _im_angle = string(_field_value); 
		else if (_field_name == "image_index") _im_frame = string(_field_value);
		else if (_field_name == "image_speed") _im_speed = string(_field_value);
		else _props += +"\n" +"      {\"resourceType\":\"GMOverriddenProperty\",\"resourceVersion\":\"1.0\",\"name\":\"\",\"propertyId\":{\"name\":\""+_field_name+"\",\"path\":\"objects/"+obj_name+"/"+obj_name+".yy\",},\"objectId\":{\"name\":\""+obj_name+"\",\"path\":\"objects/"+obj_name+"/"+obj_name+".yy\",},\"value\":\""+_field_value+"\"},";
	}
	_props += "\n" + "     ]";
}
else _props  += "[]";

//4-Add everything... this is where I use _scalex, _scalexy, _im_angle...
rm.room_string += "    {\"resourceType\":\"GMRInstance\",\"resourceVersion\":\"1.0\",\"name\":\""+"inst_"+obj_name+"_"+string(++_inst_number)+"_"+_this_level_name+"\",\"properties\":" + _props + ",\"isDnd\":false,\"objectId\":{\"name\":\""+obj_name+"\",\"path\":\"objects/"+obj_name+"/"+obj_name+".yy\",},\"inheritCode\":false,\"hasCreationCode\":false,\"colour\":4294967295,\"rotation\":0.0,\"scaleX\":" + _scalex + ",\"scaleY\":" + _scaley + ",\"imageIndex\":0,\"imageSpeed\":1.0,\"inheritedItemId\":null,\"frozen\":false,\"ignore\":false,\"inheritItemSettings\":false,\"x\":"+string(_entities[_ent].px[0])+",\"y\":"+string(_entities[_ent].px[1])+",\"tags\":[],},\n"
rm.instanceCreationOrder += "{\"name\":\""+"inst_"+obj_name+"_"+string(_inst_number)+"_"+_this_level_name+"\",\"path\":\""+rm.path+"\",},\n";

5-I also planned to **offset the x/y coordinnates** for instances in case the pivot point in LDtk is not defined as the origin in Game Maker. It is a useful feature because alignment do not behave in LDtk like Game Maker . I only did it in Evoleo's parser but not by looking at .yy file. Only by accessing sprite data at runtime... It looks like this:

// base coordinates defined in LDtk
var _x = _entities[_ent].px[0];
var _y = _entities[_ent].px[0];
// Game Maker data (from sprite not .yy file)
var spr = object_get_sprite(object_id);
var sw = sprite_get_width(spr);
var sh = sprite_get_height(spr);
var _gm_pivot_x = sprite_get_xoffset(spr) / sw;
var _gm_pivot_y = sprite_get_yoffset(spr) / sh;
// LDtk data
var lw = **_ent_def_struct**[$ _entities[_ent].__identifier]width;
var lh = **_ent_def_struct**[$ _entities[_ent].__identifier].height;
var _ld_pivot_x = **_ent_def_struct**[$ _entities[_ent].__identifier].pivot_x;
var _ld_pivot_y = **_ent_def_struct**[$ _entities[_ent].__identifier].pivot_y;
// Translate the object to keep the bounding box as it is within LDtk (otherwise, it is the center that is kept)  
_x += (_gm_pivot_x - _ld_pivot_x) * lw;
_y += (_gm_pivot_y - _ld_pivot_y) * lh;
// if  lw != sw or  lh != sh  _debug("Warning: Sprite dimensions do no match. This can cause unexpected behavior in instance scale and position.");

**Comment by Ailwuful** [comment]
I added scaling and the option to add image_speed, image_angle and image_index,
but I didn't try adding the pivot thing and I wasn't able to add variable definitions. For some reason it's always breaking the file and I couldn't figure out why so far.

**Comment by Ailwuful** [comment]
Nevermind, was able to fix it and add values in LDtk updating variable definitions.
No pivot thing, though.

**Comment by MichelVGameMaker** [comment]
Great. I was just sharing some updates I made on my side. Didn't expect you'll include this... and so soon.
What I noticed is that if the variable is not defined in the object's variables in the object .yy file the .yy room file will ignore it.
