### ISSUE TITLE
LDtk json format use "Int" instead of "Integer" for fields type

### ISSUE THREAD

**Issue by MichelVGameMaker** [Ailwuful/LDtk-Room_builder#2]
line 153: else if (fields[_n].__type == "Float" or fields[_n].__type == "Integer") {
shoud be 
else if (fields[_n].__type == "Float" or fields[_n].__type == "**Int**") {

**Comment by Ailwuful** [comment]
Thank you. I fixed it.

I also added another change to the room builder to convert Point values to a float to be used in GameMaker.

**Comment by MichelVGameMaker** [comment]
Great!
I try your importer on many test cases and it worked but it just failed to update fields on a big LDtk level I have. Everything is ok but the fields. I'll try to uderstand where it comes from because I use many features from LDtk.

I tried also to do var _field_value = string(fields[_n].__value.) on all the other types (point, etc...). It works for all of them except EntityRef. User would need to parse data from there. (I think the proper GameMaker variable type for point would be Expression. Same if the isArray of the filed is true.)
For EntityRef, I just grab the entityId with string(fields[_n].value.entityIid)... You could also replace that by the instance_name a bit like Evoleo is doing it.

Also, I did an importer to update all objects .yy to include the LDtk fields (the fields defined for entities in the def section at the begining of the JSON). I used SNAP because parsing string was a headache. Seems to work.

**Comment by Ailwuful** [comment]
There is a lot more I could potentially do with this room builder, but the idea of even making a room builder instead of something like Evoleos that parses the ldtk file at runtime is so you can do some more tweaking to levels inside GameMaker, with things that only GameMaker can do, like add filter layers.

I'll add more stuff to the room builder as the need arises.

**Comment by MichelVGameMaker** [comment]
Yes I agree. This why I find your tool very useful.

**Comment by MichelVGameMaker** [comment]
Is that ok if I reuse the code you did for parsing tiles data ? I worked on the one from Evoleo's but the stacking part does not work

**Comment by Ailwuful** [comment]
The code is free. I made it to help me make levels and put it on Github to help other people.
If it helps you can use it however you want.

**Comment by MichelVGameMaker** [comment]
Thanks. That s very kind
